name: Build packages

on: [push]

jobs:
  directories_and_excel:
    name: Check package structure and export
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Collect any new commits
        run: |
          git pull  # get any pushes made since the trigger began; without this job-to-job connections may fail

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Regularize directories
        run: python3 scripts/regularize_directories.py

      - name: Update CSVs
        run: python3 scripts/export_csvs.py

      - name: Update SBOL
        run: python3 scripts/export_sbol.py

      - name: Commit changes, ready to push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add */views
          git diff-index --quiet HEAD . || git commit -m "Automatically update exports"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  retrieve_parts:
    name: Retrieve missing parts
    needs: directories_and_excel
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Collect any new commits
        run: |
          git pull  # get any pushes made since the trigger began; without this job-to-job connections may fail

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Import parts and devices
        run: python3 scripts/import_parts.py

      - name: Convert SBOL2 imports to SBOL3
        run: python3 scripts/convert_sbol_2to3.py

      - name: Commit changes, ready to push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add */*.gb */*.fasta */*.nt
          git diff-index --quiet HEAD . || git commit -m "Automatically import referenced parts"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  build_packages:
    name: Build final packages
    needs: retrieve_parts
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Collect any new commits
        run: |
          git pull  # get any pushes made since the trigger began; without this job-to-job connections may fail

      - name: Set up Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Collate packages
        run: python3 scripts/collate_packages.py

      - name: Commit changes, ready to push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add */*.gb */*.fasta */*.nt
          git diff-index --quiet HEAD . || git commit -m "Automatically import referenced parts"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
